\c yggdrasil_bia_lana;

DROP TABLE IF EXISTS

USUARIOS, ALUNO, PROFESSOR,
PERFIL, SERVICO, DISCIPLINA,
MODULO, TRILHA, PERFIL_USA_SERVICO,
OPTATIVA_FORMA_MODULO, ALUNO_CURSA_DISCIPLINA,
USUARIO_TEM_PERFIL, MODULO_PERTENCE_TRILHA,
PROFESSOR_TUTORA_ALUNO

CASCADE;

\c postgres
DROP DATABASE IF EXISTS yggdrasil_bia_lana;
