-- Todos os alunos que entraram em 2016
SELECT AL_NOME
AS NOME_DOS_ALUNOS_QUE_ENTRARAM_EM_2016
FROM ALUNO WHERE AL_DATA_MATRICULA='2016';

-- Quantos alunos querem fazer a matéria MAC0218
SELECT COUNT(ALUNO_ID),
AS NUMERO_DE_ALUNOS_QUERENDO_FAZER_UMA_MATERIA
FROM ALUNO_CURSA_DISCIPLINA
WHERE DISCIPLINA_ID=(SELECT DS_ID FROM DISCIPLINA
WHERE DS_CODIGO='MAC0218') AND STATUS=FALSE;

-- Os créditos que Leonardo Lana já fez
SELECT SUM(DS_CREDITO_AULA + DS_CREDITO_TRAB)
AS SOMA_DOS_CREDITOS_JÁ_FEITOS
FROM DISCIPLINA WHERE DS_ID=ANY (
    SELECT DISCIPLINA_ID FROM ALUNO_CURSA_DISCIPLINA WHERE
    ALUNO_ID=(SELECT AL_ID FROM ALUNO WHERE AL_NUSP='9793735') AND
    STATUS=TRUE);

-- Se o aluno com NUSP 9793735 pode se formar
SELECT COUNT(*) AS PODE_SE_FORMAR
FROM (SELECT SUM(DS_CREDITO_AULA + DS_CREDITO_TRAB) AS OBRIGATORIA
FROM DISCIPLINA WHERE DS_ID=ANY (
    SELECT DISCIPLINA_ID FROM ALUNO_CURSA_DISCIPLINA WHERE
    ALUNO_ID=(SELECT AL_ID FROM ALUNO WHERE AL_NUSP='9793735') AND
    STATUS=TRUE) AND DS_APROVEITAMENTO=0) AS TAB1
CROSS JOIN
(SELECT SUM(DS_CREDITO_AULA + DS_CREDITO_TRAB) AS ELETIVA
FROM DISCIPLINA WHERE DS_ID=ANY (
    SELECT DISCIPLINA_ID FROM ALUNO_CURSA_DISCIPLINA WHERE
    ALUNO_ID=(SELECT AL_ID FROM ALUNO WHERE AL_NUSP='9793735') AND
    STATUS=TRUE) AND DS_APROVEITAMENTO=1) AS TAB2
WHERE OBRIGATORIA >= 5 AND ELETIVA >= 3;

-- Se o aluno com NUSP '9793735' passa na regra de estágio de 20 horas
SELECT COUNT(*) AS PODE_ESTAGIAR_20_HORAS
FROM (SELECT SUM(DS_CREDITO_AULA + DS_CREDITO_TRAB) AS OBRIGATORIA
FROM DISCIPLINA WHERE DS_ID=ANY (
    SELECT DISCIPLINA_ID FROM ALUNO_CURSA_DISCIPLINA WHERE
    ALUNO_ID=(SELECT AL_ID FROM ALUNO WHERE AL_NUSP='9793735') AND
    STATUS=TRUE) AND DS_APROVEITAMENTO=0) AS TAB1
WHERE OBRIGATORIA >= 3;
