CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY NOT NULL,
    LOGIN CHAR(320) NOT NULL,
    PASSWORD CHAR(12) NOT NULL
);

INSERT INTO USERS (LOGIN, PASSWORD)
VALUES('biamarou@gmail.com', 'esterminal');
